variables:
  LANG: en_US.UTF-8

stages:
  - build
  - lint
  - docs
  - deploy

build-pod:
  stage: build
  script:
    - pod repo update
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/WhiteNavigationController.xcworkspace -scheme WhiteNavigationController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  tags:
    - xcode11

build-example:
  stage: build
  script:
    - pod repo update
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/WhiteNavigationController.xcworkspace -scheme WhiteNavigationController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  tags:
    - xcode11

cocoapods-lint:
  stage: lint
  script:
    - pod lib lint --allow-warnings
  tags:
    - xcode11

swiftlint:
  stage: lint
  script:
    - swiftlint
  tags:
    - xcode11

jazzy-docs:
  stage: docs
  script:
    - jazzy --podspec WhiteNavigationController.podspec --output docs
  tags:
    - xcode11
  artifacts:
    paths:
      - docs

pages:
  dependencies:
    - jazzy-docs
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode11
  artifacts:
    paths:
      - public
